- hosts: all
  gather_facts: no
  tasks:
    - name: Gather facts 
      arista.eos.eos_facts:
    - debug: 
        msg: "{{ ansible_net_hostname }} - model {{ ansible_net_model }} device, serial number {{ ansible_net_serialnum }}"
        
    - name: Create config directory
      delegate_to: localhost
      ansible.builtin.file: 
        path: "/home/coder/project/LABFILES/DAY2/lab6/configs"
        state: directory

    - name: Template login banners for devices
      template: 
        src: "/home/coder/project/LABFILES/DAY2/lab6/{{ template_directory }}/banner.j2"
        dest: "/home/coder/project/LABFILES/DAY2/lab6/configs/{{ inventory_hostname }}_banner.cfg"

    - name: Load banners into devices
      arista.eos.eos_banner:
        banner: login
        state: present
        text: "{{lookup('ansible.builtin.file', '/home/coder/project/LABFILES/DAY2/lab6/configs/{{ inventory_hostname }}_banner.cfg')}}"
    
    - name: Set logging level to emergency for forwarding facility
      arista.eos.eos_logging_global:
        config:
          level:
            severity: "emergencies"

    - name: Ensure eAPI is enabled
      arista.eos.eos_eapi:
        state: "started"